name: MiningLimit
version: '${project.version}'
main: com.rickgao.MiningLimit
api-version: 1.18
authors: [ RickGao ]
description: Simple Mining Limit
softdepend: [ CoreProtect ]
commands:
  mining:
    description: Get or set player data
permissions:
  mining.bypass:
    description: Bypass mining limit
    default: false
