#MiningLimit by RickGao
#主世界 World
world_height: 50
world_max: 1000
world_add: 6
diamond: 30
gold: 15
iron: 6
iron_vein: 3
copper: 6
#下界 Nether
nether_height: 30
nether_max: 1000
nether_add: 6
ancient_debris: 120
nether_gold: 8
#增加点数周期(秒) Add point period (seconds)
add_period: 60
#警告信息 Warning Message
warning: "&e您已达到挖矿限制，请挖些其他方块再挖矿物"
